services:
  mysql-db:
    image: mysql:8.0
    container_name: banco_digital_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Banco2026@
      - MYSQL_DATABASE=banco_spring
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pBanco2026@"]
      timeout: 5s
      retries: 5
    networks:
      - banco-network

  api:
    build: .
    container_name: banco_digital_api
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/banco_spring?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      - DB_PASSWORD=Banco2026@
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - banco-network

volumes:
  mysql_data:

networks:
  banco-network:
    driver: bridge